# Generated by Django 2.1 on 2018-08-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='about',
            name='embed_video_url',
            field=models.CharField(default='https://www.youtube.com/embed/?', max_length=200),
        ),
        migrations.AddField(
            model_name='about',
            name='mission',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='about',
            name='vision',
            field=models.TextField(default=''),
        ),
    ]
